package com.icl.integrator.springapi.interceptors;

public enum DeliveryType {
	TARGET_METHOD,
	HANDLE_RESPONSE_FROM_TARGET,
	HANDLE_DELIVERY,
	HANDLE_SERV_REG,
	HANDLER_SER_IS_AVAIL,
	HANDLE_GET_SERLIST,
	HANDLER_GET_SUPP_ACTIONS,
	HANDLE_ADD_ACTION,
	HANDLE_GET_SERV_INFO,
	HANDLE_AUTO_REG;
}