package com.icl.integrator.dto.registration;

public enum ActionMethod {
	HANDLE_DELIVERY,
	HANDLE_DELIVERY_METHOD_RESPONSE,
	HANDLE_RESPONSE_FROM_TARGET,
	HANDLE_SERVER_REGISTRATION,
	HANDLE_SERVICE_IS_AVAILABLE,
	HANDLE_GET_SERVER_LIST,
	HANDLE_GET_SUPPORTED_ACTIONS,
	HANDLE_ADD_ACTION,
	HANDLE_GET_SERVICE_INFO,
	HANDLE_PING,
	HANDLE_AUTO_DETECTION_REGISTRATION,
	HANDLE_GET_ACTIONS_FOR_DELIVERY,
	HANDLE_GET_SERVICES_SUPPORTING_ACTION_TYPE,
	HANDLE_FETCH_UPDATES,
	HANDLE_REMOVE_SERVICE,
	HANDLE_EDIT_SERVICE,
	HANDLE_EDIT_ACTION
}