package com.icl.integrator.dto.registration;

public enum ActionMethod {
	GENERAL_DELIVERY,
	HANDLE_RESPONSE_FROM_TARGET,
	HANDLE_DELIVERY_RESPONSE,
	HANDLE_SERVER_REGISTRATION_RESPONSE,
	HANDLE_SERVICE_IS_AVAILABLE,
	HANDLE_GET_SERVER_LIST,
	HANDLER_GET_SUPPORTED_ACTIONS,
	HANDLE_ADD_ACTION,
	HANDLE_GET_SERVICE_INFO,
	HANDLE_PING,
	HANDLE_AUTO_DETECTION_REGISTRATION_RESPONSE
}